### PR TITLE
New comments added in Course3

### PR DESCRIPTION
**Pull request by engineersonal**
I have modified the file Course3 with some comments.

### CODE REVIEW

**Comment by SunilMunolli** [comment]
New comments added in Course3

**Comment by SunilMunolli** [comment]
New comments added in Course3

**Comment by Royalenfield350x** [comment]
New Comments added in Course3

**Comment by Ramesh-Deepika** [comment]
I have modified the file Course1

**Comment by mknavas19** [comment]
I have modified the file Course2

**Comment by amitp-0457** [comment]
Adding contents in Course3 for learning purpose

**Comment by ShashankPawas** [comment]
practice exercise

**Comment by shrey1805** [comment]
I have added a new comment in Course3

**Comment by abhi-jain-ai-engineer** [comment]
i have added a new comment in course1

**Review by sindhu199029 — COMMENTED** [review]
i have committed with new request

**Comment by sskora2023** [comment]
I have modified Course 3 file

**Comment by jitesh-rathod** [comment]
I have modified Course 2 file

**Comment by HarshRDJ** [comment]
I have modified Course 1.

**Pull request closed without merging**
